version: "3"
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
  firefox:
    image: selenium/node-firefox
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
  login:
    image: 03191992/demo:partnerportalv1
    container_name: login
    depends_on:
      - firefox
      - chrome
    environment:
      - MODULE=login.xml
      - BROWSER=firefox
      - SELENIUM_HUB=selenium-hub
    volumes:
      - /home/user/login-result:/output
  homepage:
    image: 03191992/demo:partnerportalv1
    container_name: homepage
    depends_on:
      - firefox
      - chrome
    environment:
      - MODULE=homepage.xml
      - BROWSER=chrome
      - SELENIUM_HUB=selenium-hub
    volumes:
      - /home/user/homepage-result:/output
  sqpage:
    image: 03191992/demo:partnerportalv1
    container_name: sqpage
    depends_on:
      - firefox
      - chrome
    environment:
      - MODULE=sqpage.xml
      - BROWSER=chrome
      - SELENIUM_HUB=selenium-hub
    volumes:
      - /home/user/sqpage-result:/output